# Generated by Django 5.2.6 on 2025-09-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('video_file', 'Fichier vidéo'), ('vimeo', 'Vimeo')], default='youtube', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='ID YouTube uniquement (optionnel)', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL YouTube ou Vimeo'),
        ),
    ]
