# Generated by Django 5.2.6 on 2025-09-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_lesson_lesson_type_lesson_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_points',
            field=models.TextField(blank=True, help_text="Points d'apprentissage (un par ligne)"),
        ),
    ]
